#!/usr/bin/env bash
# Base script for your tmux plug-ins
# Enable it with:
#source /path/to/this/file

#tmux_oset <opt> <new_value>
tmux_oset() { tmux set -gq "$1" "$2"; }

#tmux_oget <opt> [<default_value>]
tmux_oget() {
	if [ -z "$1" ]; then return; fi
	local V=`tmux show -gqv "$1"`
	test -z "$V" && echo "$2" || echo "$V"
}

#tmux_oupd <opt> <pair: "<old>/<new>"> {<pair>}
#tmux_oupd <opt> ${LIST_OF_PAIRS[@]}
tmux_oupd() {
	local A=($@)
	local V=`tmux_oget $1`
	for P in `seq 1 $(($#-1))` ; do
		P="${A[P]}"
		V=`echo "$V" | sed "s/$P/g"`
	done
	tmux_oset "$1" "$V"
}
