#!/bin/bash
CURRENT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
for i in `ls $CURRENT_DIR/apps/` ; do
	D_EXEC=`crudini --get $CURRENT_DIR/apps/$i "Desktop Entry" Exec`
	D_Name=`crudini --get $CURRENT_DIR/apps/$i "Desktop Entry" Name`
	echo "'${D_Name}' '' '${D_EXEC}'"
done
