#!/usr/bin/env bash
CURRENT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

if [ ! -f "$CURRENT_DIR/Apps" ]
then cp "$CURRENT_DIR/App.example" "$CURRENT_DIR/Apps"
fi

source "$CURRENT_DIR/Apps"

tmux menu -T fmenu -x P -y S "${MENU[@]//%s/"-w 29 -h 11 -x P -y S"}"
unset CURRENT_DIR MENU
